# Generated by Django 4.1.6 on 2023-02-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
