# Generated by Django 4.1.6 on 2023-02-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('core', '0002_alter_pontoturistico_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='attraction',
            field=models.ManyToManyField(to='attractions.attraction'),
        ),
    ]
