# Generated by Django 4.1.6 on 2023-02-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('core', '0003_pontoturistico_attraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='attraction',
            new_name='attractions',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='feedbacks',
            field=models.ManyToManyField(to='feedback.feedback'),
        ),
    ]
