# Generated by Django 4.1.6 on 2023-02-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('core', '0004_rename_attraction_pontoturistico_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='assessment',
            field=models.ManyToManyField(to='assessment.assessment'),
        ),
    ]
