# Generated by Django 4.1.6 on 2023-02-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0005_pontoturistico_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
            preserve_default=False,
        ),
    ]
