# Generated by Django 4.1.6 on 2023-02-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0006_pontoturistico_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
