# Generated by Django 4.1.6 on 2023-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pontoturistico_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
