# Generated by Django 4.1.6 on 2023-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='attractions'),
        ),
    ]
